# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41ba6c0c724f985815ba443cb482eaccb2495c75418fc6fc542ebf9fe04e0f634c38acb541752c536e2d706d3ea194cc63272a723d28fdd8a3a7ef2d9846fc7d

test:
  secret_key_base: 3a0bf8db0d1c8e0410e1547557286dd4739c679198d6ac79f6b38207498101647a0ef0adfe91eb10fe45c8ac5225b3f3fdf0e7d1bd8df21887b1062893984480

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
